### ISSUE TITLE
map doesn't restart after losing a round

### ISSUE THREAD

**Issue by poVoq** [nzp-team/nzportable#1059]
I am trying to run a dedicated server, which seems to work fine, but unless you manually intervene and restart the sever it just gets stuck after one round with seemingly now way to automatically reload the map for playing again.

Might be related to https://github.com/nzp-team/nzportable/issues/725

Edit: only happens occasionally, but not consistently.

**Comment by Peter0x44** [comment]
Can you fill out the issue template?

**Comment by poVoq** [comment]
**Describe the bug**
The map doesn't always restart automatically after losing a round

**To Reproduce**
Steps to reproduce the behavior:
1. run a dedicated server
2. play a round and lose
3. you see the score screen, but it does not continue until you force restart the server

**Expected behavior**
It should automatically restart the map so that people can continue playing.

**Affected Platforms**
# State which platform(s) you've seen the bug occur.
# Please also make note of any platforms you DID NOT test on.

- FTEQW (Windows, Mac, Linux, WebGL etc)

**Comment by poVoq** [comment]
I am not sure if this is a red herring or not, but it seems to happen more often if there is only one player in the game.

It also happens when you join the game as the sole player, then leave the game and afterwards rejoin. This results in being stuck in spectator mode and the map never restarts. I suspect these two have the same cause.

**Comment by MotoLegacy** [comment]
Adding a note here that I cannot reproduce this if there is only one client connected to the server.

**Comment by MotoLegacy** [comment]
Was not able to get this to reproduce ever, I think it may be related to a lack of a newline on the `localcmd("restart");` call that would have sometimes interfered if there was another command in the cbuf. I've fixed that in https://github.com/nzp-team/quakec/commit/efc004b3c5fb0ee9908aa05bf299e47af084091e , please re-open if you continue to encounter this after this commit.

**Comment by poVoq** [comment]
Still happens after the latest update.

It's possible to force it to restart via rcon commands, but then it seems to fail again on the next end of round.

The only error in the server log that looks mildly related would be this:

```
Bad entity index 1065353216
unknown-file : GiveAchievement
unknown-file : NewRound
unknown-file : Round_Core
unknown-file : StartFrame
```

**Comment by MotoLegacy** [comment]
Thanks, after more digging I found another point of error and resolved it with https://github.com/nzp-team/quakec/commit/be22fefdee01a3ee8fb7c332617c940ecdd933e6
